### ISSUE TITLE
Editpost - new option is not shown here

### ISSUE THREAD

**Issue by Eldenroot** [OUGC-Network/ougc-Show-in-Portal#2]
http://community.mybb.com/thread-120327-post-1107304.html#pid1107304

**Comment by Sama34** [comment]
I don't believe this will be added back. Why can't you use a moderation tool?

Only reason I can think of is letting users add/remove their own threads, but that could give them more power that desire (i.e: being able to mess with your index if they decide to remove all of their threads).
