### ISSUE TITLE
Common users without permissions can delete announcements

### ISSUE THREAD

**Issue by Eldenroot** [OUGC-Network/ougc-Show-in-Portal#4]
Common users without permissions can delete announcements from portal page. I dont know how, but they can everytime they reply in the thread which is also showed in portal page.

**Comment by Sama34** [comment]
Can you replicate in the master branch? I can't remember if I pushed the fix to this.

**Comment by Eldenroot** [comment]
I fixed this (hacky way) - I removed your code from quick reply. I will try to replicate with your master

**Comment by Sama34** [comment]
I will try to push changes ASAP on the future, thanks @Cu8eR

**Comment by kingsolomon17** [comment]
How do i fix this pls help me 
Thread auto remove from portal when user comment
