### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by kingsolomon17** [OUGC-Network/ougc-Show-in-Portal#6]
When i install the plugin ,
And user post it still show on portal without moderator or admin 
Moving it pls help

**Comment by Sama34** [comment]
You are making me guess too much. Please be more descriptive. By default, no threads should be displayed in portal if installed properly.

**Comment by kingsolomon17** [comment]
Yes i did install it well, i have but when i use another acct to post it still show on portal

**Comment by kingsolomon17** [comment]
And here is the variable i use in portal {$latestthreads}
Here is my url www.sologet.com

**Comment by Sama34** [comment]
{$latestthreads} is a default variable not added by this plugin.

**Comment by kingsolomon17** [comment]
I dont understand

**Comment by Sama34** [comment]
There you go, that is the problem.

I can't guess your mistake; you need to provide information.

**Comment by kingsolomon17** [comment]
I have just find out that am using another variable 
My mobile didnt have the portal post variable 
The {$latestthreads} is for recent post not portal thread 
Thanks very much bro 
But get one thing 
I want to make the show only title and thumbnail  is that possible bro

**Comment by Sama34** [comment]
You can edit the _portal_announcement_ template to fit your needs. But attachments aren't displayed inside the portal.

I'm glad you fixed it but please for support refer to the forums.

**Comment by kingsolomon17** [comment]
Thanks i will try 
www.sologet.com

**Comment by kingsolomon17** [comment]
But bro i dont see the moderator tools on creating thread or editing it please give me the variable

**Comment by Sama34** [comment]
Please refer to the community. I'm sure your inquiry has been solved before and this is just to report bugs.
